#! /bin/bash

for alfa1 in $(seq 5.0 0.25 6); do
	for alfa2 in $(seq 4 0.2 3); do
		echo -en "$alfa1\t"
		echo -en "$alfa2\t"
		scripts/run_vad.sh $alfa1 $alfa2 | grep TOTAL | sort -t: -k2n
	done 
done	
