#! /bin/bash

for alfa1 in $(seq 5.05 0.01 5.15); do
	for alfa2 in $(seq 4.9 0.1 5.0); do
		echo -en "$alfa1\t"
		echo -en "$alfa2\t"
		scripts/run_vad.sh $alfa1 $alfa2 | grep TOTAL | sort -t: -k2n
	done 
done	
